apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring-app.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ include "monitoring-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "monitoring-app.name" . }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: 80

