apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring-app.fullname" . }}-server
  labels:
    app.kubernetes.io/name: {{ include "monitoring-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "monitoring-app.name" . }}
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 3001
      targetPort: {{ .Values.server.port }}

