name: CI - Build & Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check DOCKERHUB_TOKEN presence
        run: |
          if [ -z "${DOCKERHUB_TOKEN}" ]; then
            echo "DOCKERHUB_TOKEN is missing (Repository secret not set)";
            exit 1;
          else
            echo "Token present";
          fi
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: shruti29044
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push server image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: ${{ github.event_name != 'pull_request' }}
          tags: shruti29044/monitoring-server:${{ github.sha }}

      - name: Build & push web image
        uses: docker/build-push-action@v6
        with:
          context: ./web
          push: ${{ github.event_name != 'pull_request' }}
          tags: shruti29044/monitoring-web:${{ github.sha }}


